### DISCUSSION TITLE
Non-Rheem compatibility?

### DISCUSSION THREAD

**Discussion by super7oas7** [esphome-econet/esphome-econet#393] [Q&A]
Apologies for the very dumb question but I figured I'd ask...

Is there any reason to believe this will work for non-Rheem water heaters? I have a modern Bradford White unit with an RJ11 port but REALLY dont want to buy their "Bradford Connect" adapter which is basically a $300 ESP32 and some plastic.

**Comment by rsmanning** [comment]
I have a Richmond Heatpump water heater made by Rheem and it doesn't work with this integration, still has the econet controller and phone port on the side...

**Reply by gotmoo** [reply]
I installed a Richmond heat pump water heater from [Menards](https://www.menards.com/main/search.html?search=richmond+wifi+heat+pump+water+heater) and was surprised their support was just straight up Rheem.

**Reply by NobleWolf** [reply]
@rsmanning thank you for letting us know. I was just about to buy the components. Thank you again.

**Reply by gotmoo** [reply]
> @rsmanning thank you for letting us know. I was just about to buy the components. Thank you again.

I did get it working on the Richmond hybrid water heater:
![image](https://github.com/user-attachments/assets/849d31ae-89a0-4216-98cf-f1997e6de024)

I used these parts and ports to get it working:
* [Wemos D1 Mini](https://www.amazon.com/wemos-d1-mini/s?k=wemos+d1+mini) with [TTL to RS485 Adapter Module](https://www.amazon.com/s?k=TTL+to+RS485+Adapter+Module)
  * Connect from `Wemos D1` to `RS485 Module`
    - `3.3v` > `VCC`
    - `GND` > `GND`
    - `D5` > `RXD`
    - `D6` > `TXD`
  * Requires change to `tx_pin: D6` and `rx_pin: D5`

**Reply by barndawgie** [reply]
> I did get it working on the Richmond hybrid water heater:

What model of water heater, if you can share?

**Reply by gotmoo** [reply]
> > I did get it working on the Richmond hybrid water heater:
> 
> What model of water heater, if you can share?

`10E50-HP530` is the model from the Menards receipt, but `10E50-HP5+30` is what HA reports. The reported software version is `WH-HPW5-H6-01-01`

**Comment by NobleWolf** [comment]
Did you have to do anything for the software, or did installing it
directly on the D1 Mini with your wiring changes work?

On Fri, Jan 24, 2025 at 10:24 PM Johan ***@***.***> wrote:

> @rsmanning <https://github.com/rsmanning> thank you for letting us know.
> I was just about to buy the components. Thank you again.
>
> I did get it working on the Richmond hybrid water heater:
> image.png (view on web)
> <https://github.com/user-attachments/assets/849d31ae-89a0-4216-98cf-f1997e6de024>
>
> I used these parts and ports to get it working:
>
>    - Wemos D1 Mini
>    <https://www.amazon.com/wemos-d1-mini/s?k=wemos+d1+mini> with TTL to
>    RS485 Adapter Module
>    <https://www.amazon.com/s?k=TTL+to+RS485+Adapter+Module>
>       - Connect from Wemos D1 to RS485 Module
>          - 3.3v > VCC
>          - GND > GND
>          - D5 > RXD
>          - D6 > TXD
>       - Requires change to tx_pin: D6 and rx_pin: D5
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome-econet/esphome-econet/discussions/393#discussioncomment-11949663>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGNMGEPIYZLLT7KHX4WTKL2MMGZPAVCNFSM6AAAAABVZYL5J2VHI2DSMVQWIX3LMV43URDJONRXK43TNFXW4Q3PNVWWK3TUHMYTCOJUHE3DMMY>
> .
> You are receiving this because you commented.Message ID:
> <esphome-econet/esphome-econet/repo-discussions/393/comments/11949663@
> github.com>
>


-- 
Sincerely,
  Josh

**Comment by gotmoo** [comment]
I think it's all default. I made a "waterheater.yaml" in ESP Home, and then replaced all the contents with this:

``` yaml
substitutions:
  tx_pin: D6
  rx_pin: D5
  platform: esp8266
  board: d1_mini

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_heatpump_water_heater.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/build-yaml/${name}-${platform}.yaml@${github_ref}
  import_full_config: false

# Uncomment the below to use Wi-Fi settings from your secrets.yaml file
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

My setup had stopped reporting and I didn't notice this for a few days. I did notice these messages in the log and I'm wondering if that is due to the ESP8266:
![image](https://github.com/user-attachments/assets/795bd5f2-d1ec-4aba-9bfa-4fa9c5e5bd2b)

When I have some time later this week I will try to swap it for an ESP32 module and report back what I find.
