### DISCUSSION TITLE
Does this project support Furnaces with air source heat pump systems?

### DISCUSSION THREAD

**Discussion by stefanhra** [esphome-econet/esphome-econet#421] [General]
In particular can anyone tell me if the equipment below is supported by this project?

Furnace - R962V0603A17M4S
Heat pump - RD17AZ24AJ3N

I know it is very specific but I may be purchasing these units.

Cool project BTW. Keep up the good work.

**Comment by Daniel-dev22** [comment]
> In particular can anyone tell me if the equipment below is supported by this project?
> 
> Furnace - R962V0603A17M4S
> Heat pump - RD17AZ24AJ3N
> 
> I know it is very specific but I may be purchasing these units.
> 
> Cool project BTW. Keep up the good work. 

It should. There's a few users with a heat pump and backup furnace.

**Comment by Zerosk83** [comment]
So I just went through this today, and documented the steps I took to get things working. 

1. Confirm all of your equipment, model #s etc. 
In my case I have the following:
	1) Furnace Model Number: U96VA0852521MSB (96% Rheem Prestige® Series Two-Stage Variable Speed, Multi-position Gas Furnace)
	2) Outdoor unit model number: UP2036BJVCA (3-ton Ruud UP20 Ultra Series Air Source Heat Pump)
	3) Standard RJ11 telephone cable (BC-64SS014F 6P4C from Mouser) ($3.29 CAD)
	4) AtomS3Lite M5Stack (C124 from Mouser) ($11.60 CAD)
	5) RS485 Base M5Stack (A131 from Mouser) ($14.43 CAD)
2. Go to the esphome econet Github page and find the sample .yaml file that matches your equipment. 
https://github.com/esphome-econet/esphome-econet/blob/main/build-yaml/
In my case, it was econet-hvac_furnace-esp32s3.yaml since I'm using an esp32 S3 device. 
3. Because I have an outdoor unit and am using wifi, I uncomment/delete the # on lines 15-18 and 33-35. I also added sections regarding naming and set an API key
4. I had esphome running already inside HomeAssistant, from the Add-On store. If you don't yet, go do that now. 
5. I initially plugged the combined RS485+AtomS3Lite into my PC using a USB-C cable, and then used https://esphome-econet.github.io/install/ to install the "HVAC - Furnace" build and configure wifi etc. This gives you a bare bones config inside esphome that you can customize easily
6. Adopt the device in esphome
7. Edit the adopted device, and copy in the custom config you made in step 3. You can keep the API key it is using already, it will make things simpler. Save the config and X out, back to esphome.
8. Click the triple dots >  Validate. It should take a minute but eventually should say things are good. 
9. Click triple dots again > Install > Manual Download > Modern/Factory Build (You can try "Plug into this computer", but I had issues with it)
10. New Device > Open ESPHOME WEB > Connect > Choose your device (should be something other than COM1) > Apply the .bin file we just downloaded
11. Cut the RJ11 cable, strip it and wire it up to your AtomS3 as explained on the github page (https://github.com/esphome-econet/esphome-econet/wiki/Recommended-Hardware-Purchase-and-Setup-Instructions)
12. Plug the RJ11 cable into the diagnostic port on your furnace, run it through the cable hole and close the door. Power your device with a USB charger of some sort. For me, the diagnostic port was accessible from the bottom door, right in the middle of the motherboard. 
13. Check Home assistant > Settings > Devices & Services > ESPHome > 1 Device. You should see all of your HVAC info after a minute, and can begin adding stuff to dashboards!

**Comment by Zerosk83** [comment]
Here's my final yaml config file if it helps anyone:

```
---
substitutions:
  tx_pin: GPIO6
  rx_pin: GPIO5
  board: esp32-s3-devkitc-1
  platform: esp32
  variant: esp32s3
  name: econet-hvac_furnace
  friendly_name: Rheem HVAC

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_hvac_furnace.yaml
  econet-hvac-odu:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_hvac_odu.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/build-yaml/${name}-${variant}.yaml@${github_ref}
  import_full_config: false

esphome:
  platform: !remove
  board: !remove
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  board: ${board}
  variant: ${variant}

api:
  encryption:
    key: XXXXXXXXXXXXXXXXXXXXXXXXX

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
