### DISCUSSION TITLE
m5stick c with AOZ1282CI?

### DISCUSSION THREAD

**Discussion by drobtravels** [esphome-econet/esphome-econet#449] [Q&A] [answered]
I already have an unused m5stick C.  Can I use that with the [M5StickC RS485 HAT AOZ1282CI](https://shop.m5stack.com/products/m5stickc-rs485-hat-aoz1282ci?variant=17456934584410) with no issue?

I read the [wiki](https://github.com/esphome-econet/esphome-econet/wiki/Proven-ESP-Hardware) and see some models require a pin change, but reading the description of each model.. I'm not clear what is different or how to make that pin change.  Is this just updating the YAML config?

Thanks for the guidance!

**Comment by barndawgie** [comment, marked as answer]
That should work, I think.

Pin change is just a YAML update to override the RX and TX pin variables. If you take a look at the defaults for the esp32, they align to the GPIO pins that hit the RX and TX pins on the recommended RS485 interface. It looks like that's probably GPIO 0 and GPIO 26 with that device, but will depend on your ESP device too.

**Comment by sbman** [comment]
Did you get the M5StickC setup working?  I have the xame setup with an M5StickCPlus, and RS485 Hat and have changed the yaml as follows:

```
substitutions:
  tx_pin: GPIO00
  rx_pin: GPIO26
  board: m5stick-c
  platform: esp32
#  variant: esp32c3

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_heatpump_water_heater.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/build-yaml/${name}-${variant}.yaml@${github_ref}
  import_full_config: false

```
Everything builds and installs correctly from the command line, it flashes to the board, and then it comes up on my Wifi. I see it discovered in home assistant and all of the entities load, but none of them have values. I've tried swapping the data wires A/B Green/Red and verified with a multimeter that the connections are correct. I've tried swapping the RX/TX values in the YAML and get the same results.  The logs from the device output this message over and over again:

[16:35:52][W][econet:195]: New read request while waiting response for previous read request
