### ISSUE TITLE
HVAC: Fan Control Doesn't Work When Using Schedule

### ISSUE THREAD

**Issue by stockmopar** [esphome-econet/esphome-econet#177]
https://github.com/esphome-econet/esphome-econet/blob/176a2a6edb0b7b29e2ab1e90d15b2bac81fbf372/econet_hvac.yaml#L30

Here this references "STATNFAN" but this is the value only used when "N"o schedule is active. When a schedule is active I believe "STAT_FAN" needs to be used.

**Comment by tronikos** [comment]
See https://github.com/esphome-econet/esphome-econet/wiki/Objects how you could test whether STAT_FAN works.
Add the following:

```yaml
text_sensor:
  - platform: econet
    name: "STAT_FAN text"
    sensor_datapoint: STAT_FAN

number:
  - platform: econet
    name: "STAT_FAN number"
    number_datapoint: STAT_FAN
    min_value: 0
    max_value: 100
    step: 1
    mode: box
```
