### ISSUE TITLE
example-local.yaml fails config check when "files" is used

### ISSUE THREAD

**Issue by justbruce** [esphome-econet/esphome-econet#202]
example-local.yaml attempts to use "files: [] " for a multiple file !include.

  While this seems logical, and passes the human-readability test, when actually attempting to config or compile this file with the line enabled, esphome throws error after error.

  I've searched the documentation, and I can't find a definition of !include that allows multiple files in this manner.

**Comment by barndawgie** [comment]
That model appears to be supported for emote files, but not local ones: https://esphome.io/guides/configuration-types.html?highlight=packages#local-packages

I can repro the problem as well. If I set my example-local.yaml as follows:
```yaml
packages:
  econet: !include
    file: [econet_hvac.yaml, econet_hvac_odu.yaml]
    vars:
      external_components_source: components
```

I get:

```
INFO ESPHome 2023.11.4
INFO Reading configuration example-local.yaml...
ERROR Error while reading config: Invalid YAML syntax:

Must include 'file'
  in "example-local.yaml", line 3, column 11:
      econet: !include
              ^
```
