### ISSUE TITLE
Hotwater / Vacatime are unsupported - Gen3 Heatpump

### ISSUE THREAD

**Issue by Ylianst** [esphome-econet/esphome-econet#236]
In looking at my Rheem Heatpump Water Header on ESPHOME-ECONET logs, I am seeing these errors periodically.

![image](https://github.com/esphome-econet/esphome-econet/assets/1319013/f752c6af-2a1a-4580-a363-fdd856b66733)

The two important lines are here:

```
[23:22:09][W][econet:337]:   HOTWATER : UNSUPPORTED
[23:22:09][W][econet:337]:   VACATIME : UNSUPPORTED
```

If I recall correctly, I have a Gen3 (with the color LCD display). The integration seems to work well otherwise, but if there is a way to remove these errors, it would be great.

My ESP-HOME config file:

```
---
substitutions:
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_heatpump_water_heater.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hotwaterheater Fallback Hotspot"
    password: "xxxxxxxxxxxxxx"

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  password: "xxxxxxxxxxxxxxxxxxxx"
```

Thanks for the wonderful work!
Ylian

**Comment by tronikos** [comment]
See https://github.com/esphome-econet/esphome-econet/issues/203#issuecomment-1827130082
I guess we need to add a FAQ and mention this there.

**Comment by barndawgie** [comment]
Once https://github.com/esphome/esphome/pull/5821 is merged it should provide a good option for removing components that aren't supported on certain devices.

**Comment by Ylianst** [comment]
Nice. Indeed this fixed it. Here is my new configuration file:

```
---
substitutions:
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_heatpump_water_heater.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hotwaterheater Fallback Hotspot"
    password: "xxxxxxxxxxxxxx"

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  password: "xxxxxxxxxxxxxxxxxxxx"

sensor:
  - id: !extend hot_water
    request_mod: none
    internal: true
number:
  - id: !extend vacatime
    request_mod: none
    internal: true
```

I added the 8 last lines. It correctly removed the two features:

![image](https://github.com/esphome-econet/esphome-econet/assets/1319013/bcc4ab7c-230b-4bd1-9250-82e51aa8c3f7)
