### ISSUE TITLE
Utilize LED on the M5 to Indicate Power / Activity

### ISSUE THREAD

**Issue by stockmopar** [esphome-econet/esphome-econet#241]

**Comment by stockmopar** [comment]
Looks like here's an example of controlling the LED:

https://github.com/m5stack/M5Atom/blob/00f5a14e1cf6c25d16a4dd011a5f971bca29ec43/examples/Basics/FactoryTest/ATOM_LITE/ATOM_LITE.ino#L4

**Comment by stockmopar** [comment]
This page:
https://community.home-assistant.io/t/atom-lite-rgb-led-turns-on-by-itself/452852/6

Gives this yaml to try:
```
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 27
    num_leds: 1
    rmt_channel: 0
    chipset: SK6812
    id: status_led
    name: ${name} Light
    effects:
      - random:
      - flicker:
      - addressable_rainbow:
```

**Comment by barndawgie** [comment]
This is my Atom Lite config:
```
---
binary_sensor:
  - platform: gpio
    id: atom_button
    pin:
      number: GPIO39
      inverted: true
    name: "ATOM Lite Button"
    icon: "mdi:gesture-tap-button"
    entity_category: "config"
    disabled_by_default: true

light:
  - platform: esp32_rmt_led_strip
    name: "ATOM Lite LED"
    id: atom_led
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rmt_channel: 0
    rgb_order: GRB
    icon: "mdi:led-off"
    entity_category: "config"
    disabled_by_default: true

output:
  - platform: template
    id: atom_led_output
    type: binary
    write_action:
      if:
        condition:
          lambda: return state;
        then:
          - light.turn_on: atom_led
        else:
          - light.turn_off: atom_led

# esp32_improv:
#   authorizer: atom_button
#   status_indicator: atom_led_output
```

I haven't been able to get the BLE Improv working. Or rather, it works, but results in repeated wi-fi disconnects that I haven't been able to troubleshoot. But the light and button for sure work. I haven't figured out how to control the LED color yet, though. Maybe those "effects" are what I need.
