### ISSUE TITLE
Enhancement:   Request for LP / NG selector in Controls section

### ISSUE THREAD

**Issue by fireheadman** [esphome-econet/esphome-econet#305]
Would be nice to offer a selector on fuel type...
![image](https://github.com/esphome-econet/esphome-econet/assets/19847195/b9d27568-dfc5-4294-a6a3-d1e0cebd4bf9)

Played around with this a little, but I'm not savvy enough to get the code correct....
This would populate a selector, but it didn't to my knowledge actaually do anything, hoping maybe someone with more experience can do this?

This was placed in the ESPHome deployment code, saved, then install

```
select:
## furnace_kbtus_per_m3: "88.852" # Natural Gas = approx 35.300, Propane = approx 88.852
  - platform: template
    name: Fuel Type
    id: furnace_kbtus_per_m3
    optimistic: True
    options:
      - NG
      - LP
    icon: "mdi:fuel"
```
