### ISSUE TITLE
Not seeing power sensor data on Rheem Hybrid electric water heater

### ISSUE THREAD

**Issue by kenyonj** [esphome-econet/esphome-econet#325]
My water heater isn't showing power information. Is it supported with this water heater?

Rheem 50 gal hybrid electric
Model # XE50T10HD50U0

![Image](https://github.com/esphome-econet/esphome-econet/assets/4008677/6f00e699-a7fe-4f24-9ee7-89eaccccfb2e)

My config:

```yml
substitutions:
  name: econet-hpwh
  friendly_name: Water Heater
packages:
  esphome-econet.esphome-econet: github://esphome-econet/esphome-econet/build-yaml/econet-hpwh-esp32.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ...
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
