### ISSUE TITLE
Add XE50T12CS55U0 to proven model compatibility wiki page

### ISSUE THREAD

**Issue by meyerds** [esphome-econet/esphome-econet#378]
All of the sensors and controls seem to work. The only thing I'm not sure about is - there seems to be an "energy saver" preset available alongside the default-for-this-model "performance" preset. Since this is an electric tank model, not a hybrid, I don't think the "energy saver" preset is relevant?

**Comment by tronikos** [comment]
Added it to the wiki. You can remove it with:

```yaml
climate:
  - id: !extend econet_climate
    custom_presets:
      0: !remove
```
