### ISSUE TITLE
Getting error of "[econet:342]:   I_RMSVAL : UNSUPPORTED" with latest update

### ISSUE THREAD

**Issue by BigThunderSR** [esphome-econet/esphome-econet#396]
I'm getting the following error since the latest update from today because my model does not support this sensor:

```[econet:342]:   I_RMSVAL : UNSUPPORTED```

How do I disable this sensor in my YAML file? Thanks.

**Comment by tronikos** [comment]
I missed adding id to this sensor to allow extending it and removing it. I added ids to everything else except this. Let me fix it.

**Comment by tronikos** [comment]
To remove it add the following to your yaml:

```yaml
sensor:
  - id: !remove ac_current_rms
```

Make sure you have `refresh: 0s` otherwise ESPHome is caching repos for, I think, a day. This is what I have:

```yaml
packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: build-yaml/econet-hpwh-esp8266.yaml
    refresh: 0s
```
