### ISSUE TITLE
Add 'hvac_write_float_from_address' HA Service

### ISSUE THREAD

**Issue by justbruce** [esphome-econet/esphome-econet#401]
The current 'hvac_write_float' defaults to the 0x340 FROM address [the wifi module].  Many writes are not accepted/immediately overwritten by the thermostat from this address [for example FILTUSED and FILT_CHG].  

  For testing reasons [at present], it would be helpful to be able to write a float value with a FROM address of the Furnace, or the ODU.   

Would it be possible to get an HA Service like this?  To more effectively explore the protocol, at least?

**Comment by tronikos** [comment]
#402 adds such as a service.

Can you verify it works before merging it?

You can use it by replacing the package in your yaml with:

**Don't forget to update the file below to match your device**

```yaml
packages:
  econet:
    url: https://github.com/tronikos/esphome-econet
    ref: write_float_from_address
    file: build-yaml/econet-hpwh-esp8266.yaml
    refresh: 0s
```
