### ISSUE TITLE
Provide Better Handling of Alerts and Populate Specific Alert Information

### ISSUE THREAD

**Issue by barndawgie** [esphome-econet/esphome-econet#61]
Currently, our configurations  don't include any details on Alerts. We need to get both Alert State (i.e. is there an active alert) and specific details on the active alert into the basic configurations.

This issue is blocked on the moment on getting an actual Alert State on a device so we can see how the ALRMALRT and ALMCODE1 states are populated.

Page 27 of this document provide some further details on Alarm usecases (at least for HPWH's):
https://s3.amazonaws.com/WebPartners/ProductDocuments/93804014-4C4E-4270-BC88-1163623DA4C8.pdf

**Comment by tronikos** [comment]
I was able to get 2 alerts by disconnecting the temperature sensors from the elements. I initially disconnected just the lower one and the value I got was 1. Unfortunately I didn't get any value for ALMCODE1 or the rest in the ESPHome logs in the responses of the read requests. Also, not sure why but the binary sensor stayed OK the whole time. The count sensor increased to 2.

This was my config:

```yaml
binary_sensor:
  - platform: econet
    name: "Active Alerts"
    sensor_datapoint: ALRMALRT
    device_class: "problem"

sensor:
  - platform: econet
    name: "Active Alerts"
    sensor_datapoint: ALRMALRT
    accuracy_decimals: 0
    icon: "mdi:water-boiler-alert"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Alert 1"
    sensor_datapoint: ALMCODE1
    icon: "mdi:water-boiler-alert"
    state_class: "measurement"
    entity_category: "diagnostic"

text_sensor:
  - platform: econet
    name: "Alert 1"
    sensor_datapoint: ALMCODE1
    icon: "mdi:water-boiler-alert"
    entity_category: "diagnostic"
```

This is the history in Home Assistant:
![image](https://github.com/esphome-econet/esphome-econet/assets/9987465/5804ed6d-4d56-4a57-8135-96340a56c58f)

So let's only add the following:

```yaml
sensor:
  - platform: econet
    name: "Active Alerts"
    sensor_datapoint: ALRMALRT
    accuracy_decimals: 0
    icon: "mdi:water-boiler-alert"
    state_class: "measurement"
    entity_category: "diagnostic"
```
